### ISSUE TITLE
Problems starting container

### ISSUE THREAD

**Issue by robertodocampo** [dmart28/gcplot-docker#1]
When i try to run the container on my RedHat  i receive the next message and the container not finalize the start process..

GCPlot instance is initialized
Exception in thread "main" org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 6 in XML document from class path resource [applicationContext.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 120; cvc-elt.1: Cannot find the declaration of element 'beans'.
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:399)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:181)

Can you help me

**Comment by dmart28** [comment]
Hi @robertodocampo 
Thanks for bringing this to attention, this seems to be because of the absence of internet connection inside the Docker container.
I will publish the fixed version tomorrow and will update you about that (so it will no longer require internet inside the container)

**Comment by dmart28** [comment]
@robertodocampo this was fixed, please pull the latest version (2.0.1)

**Comment by robertodocampo** [comment]
Thanks a lot! Runs perfectly!
