### ISSUE TITLE
com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1:9042] Cannot connect

### ISSUE THREAD

**Issue by bobogu23** [dmart28/gcplot-docker#4]
I first time to use gcplot. The gcplot docker container version is 2.0.2.  I use docker run -d -p 8080:80 gcplot/gcplot:2.0.2 to start gcplot,but it does not work.I can not request localhost:8080. 

I use docker desktop on MacOs,Version is 2.1.0.1(37199),Engine:19.03.1

Please help,here is the docker log below.

Starting OrientDB ...
Starting OrientDB server daemon...
Waiting for the OrientDB 2424 port to be opened ...
Creating OrientDB database ...

OrientDB console v.2.2.13 (build 2.2.x@r90d7caa1e4af3fad86594e592c64dc1202558ab1; 2016-11-15 12:04:05+0000) www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

orientdb> CREATE DATABASE remote:localhost:2424/gcplot admin admin plocal

Creating database [remote:localhost:2424/gcplot] using the storage type [plocal]...
Connecting to database [remote:localhost:2424/gcplot] with user 'admin'...OK
Database created successfully.

Current database is: remote:localhost:2424/gcplot
Starting Cassandra ...
Waiting for the Cassandra 9042  port to be opened ...
Performing CQL initialization ...

Warnings :
Materialized views are experimental and are not recommended for production use.

Running gcserver service ...
Starting gcserver ...
gcserver is not running ...
gcserver started ...
GCPlot instance is initialized
Dec 05, 2019 4:39:50 AM io.vertx.core.spi.resolver.ResolverProvider
INFO: Using the default address resolver as the dns resolver could not be loaded
Exception in thread "main" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'analyseController': Unsatisfied dependency expressed through field 'analyseRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cassandraGCAnalyseRepository' defined in class path resource [applicationContext-cassandra.xml]: Cannot resolve reference to bean 'cassandraConnector' while setting bean property 'connector'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cassandraConnector' defined in class path resource [applicationContext-cassandra.xml]: Invocation of init method failed; nested exception is com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1:9042] Cannot connect))
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.gcplot.bootstrap.Bootstrap.run(Bootstrap.java:68)
	at com.gcplot.bootstrap.Bootstrap.main(Bootstrap.java:32)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cassandraGCAnalyseRepository' defined in class path resource [applicationContext-cassandra.xml]: Cannot resolve reference to bean 'cassandraConnector' while setting bean property 'connector'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cassandraConnector' defined in class path resource [applicationContext-cassandra.xml]: Invocation of init method failed; nested exception is com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1:9042] Cannot connect))

**Comment by quazard** [comment]
Maybe you have already figured it out, but in case someone else get this error, just increase the memory assigned to Docker in preferences/resources or adjust the memory for Cassandra DB through environment variables when running the docker container.

**Comment by fernaspiazu** [comment]
I've got the same error despite having increased memory for Cassandra and Docker Desktop...
