### ISSUE TITLE
Startup Failed using docker command

### ISSUE THREAD

**Issue by 6harat** [dmart28/gcplot-docker#5]
```
Starting OrientDB ...
Starting OrientDB server daemon...
Waiting for the OrientDB 2424 port to be opened ...
Creating OrientDB database ...

OrientDB console v.2.2.13 (build 2.2.x@r90d7caa1e4af3fad86594e592c64dc1202558ab1; 2016-11-15 12:04:05+0000) www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

orientdb> CREATE DATABASE remote:localhost:2424/gcplot admin admin plocal

Creating database [remote:localhost:2424/gcplot] using the storage type [plocal]...
Connecting to database [remote:localhost:2424/gcplot] with user 'admin'...OK
Database created successfully.

Current database is: remote:localhost:2424/gcplot
Starting Cassandra ...
Waiting for the Cassandra 9042  port to be opened ...
Performing CQL initialization ...
Running gcserver service ...
Starting gcserver ...
gcserver started ...
GCPlot instance is initialized
Jul 08, 2020 10:41:21 AM io.vertx.core.spi.resolver.ResolverProvider
INFO: Using the default address resolver as the dns resolver could not be loaded
Exception in thread "main" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.gcplot.controllers.DefaultDispatcherHandlers#0': Unsatisfied dependency expressed through method 'setDispatcher' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dispatcher' defined in class path resource [applicationContext-web.xml]: Cannot resolve reference to bean 'accountRepository' while setting bean property 'accountRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountRepository' defined in class path resource [applicationContext-orientdb.xml]: Invocation of init method failed; nested exception is com.orientechnologies.orient.core.exception.OStorageException: Cannot create a connection to remote server address(es): [127.0.0.1:2424]
	DB name="gcplot"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:667)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.gcplot.bootstrap.Bootstrap.run(Bootstrap.java:68)
	at com.gcplot.bootstrap.Bootstrap.main(Bootstrap.java:32)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dispatcher' defined in class path resource [applicationContext-web.xml]: Cannot resolve reference to bean 'accountRepository' while setting bean property 'accountRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountRepository' defined in class path resource [applicationContext-orientdb.xml]: Invocation of init method failed; nested exception is com.orientechnologies.orient.core.exception.OStorageException: Cannot create a connection to remote server address(es): [127.0.0.1:2424]
	DB name="gcplot"
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1531)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1276)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:659)
	... 16 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountRepository' defined in class path resource [applicationContext-orientdb.xml]: Invocation of init method failed; nested exception is com.orientechnologies.orient.core.exception.OStorageException: Cannot create a connection to remote server address(es): [127.0.0.1:2424]
	DB name="gcplot"
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	... 29 more
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot create a connection to remote server address(es): [127.0.0.1:2424]
	DB name="gcplot"
	at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:2080)
	at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1978)
	at com.orientechnologies.orient.client.remote.OStorageRemote.open(OStorageRemote.java:359)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:259)
	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:56)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.open(OObjectDatabaseTx.java:120)
	at com.gcplot.repository.AbstractOrientDbRepository.db(AbstractOrientDbRepository.java:90)
	at com.gcplot.repository.AbstractOrientDbRepository.init(AbstractOrientDbRepository.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1758)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1695)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 36 more
Jul 08, 2020 10:42:05 AM com.orientechnologies.common.log.OLogManager log
INFO: Orient Engine is shutting down...
```

(source: docker logs)
Environment:
MacOS: 10.13.6
Docker Version: 19.03.8, build afacb8b

**Comment by prabinsh** [comment]
Any update this issue?

**Comment by harneet85** [comment]
I am facing a similar issue 

root:~# docker container ls
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
CONTAINER ID  IMAGE                           COMMAND     CREATED         STATUS            PORTS               NAMES
0b1fdb9bfad3  docker.io/gcplot/gcplot:latest  /start.sh   27 minutes ago  Up 7 minutes ago  0.0.0.0:80->80/tcp  frosty_keldysh
root:~# docker container logs frosty_keldysh
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Starting OrientDB ...
Starting OrientDB server daemon...
su: System error
Waiting for the OrientDB 2424 port to be opened ...
Starting OrientDB ...
Starting OrientDB server daemon...
su: System error
Waiting for the OrientDB 2424 port to be opened ...
root:~#

**Comment by harneet85** [comment]
I am facing similar issue 


root:~# docker container ls
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
CONTAINER ID  IMAGE                           COMMAND     CREATED         STATUS            PORTS               NAMES
0b1fdb9bfad3  docker.io/gcplot/gcplot:latest  /start.sh   27 minutes ago  Up 7 minutes ago  0.0.0.0:80->80/tcp  frosty_keldysh
root:~# docker container logs frosty_keldysh
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Starting OrientDB ...
Starting OrientDB server daemon...
su: System error
Waiting for the OrientDB 2424 port to be opened ...
Starting OrientDB ...
Starting OrientDB server daemon...
su: System error
Waiting for the OrientDB 2424 port to be opened ...
root:~#
